#!/usr/bin/env python3

import argparse
import os
import sys

from jinja2 import Environment, FileSystemLoader, TemplateError
from context import context

PATH = os.path.dirname(os.path.abspath(__file__))
ENVIRONMENT = Environment(
    autoescape=False,
    loader=FileSystemLoader(PATH),
    trim_blocks=False,
)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description=__doc__,
    )
    parser.add_argument(
        'template',
        type=str,
        help="Template file",
    )
    parser.add_argument(
        'output',
        type=argparse.FileType('w'),
        help="output file",
    )
    args = parser.parse_args()

    try:
        result = ENVIRONMENT.get_template(args.template).render(context)
    except TemplateError as exn:
        sys.exit("%s: %s" % (type(exn).__name__, exn))
    args.output.write(result)
